server:
  port: 7001

#Eureka配置
eureka:
  instance:
   hostname: localhost
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己（这里是eureka服务器本身，不需要注册）
    fetch-registry: false #如果为false则表示自己为注册中心
    service-url: #监控页面
      defaultZone: http://127.0.0.1:7002/eureka/,http://localhost:7003/eureka/
