server:
  port: 8001

mybatis:
  type-aliases-package: com.baozi.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springclouddb01?useUnicode=true&charaterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://127.0.0.1:7002/eureka/
  instance:
    instance-id: springcloud-provider-Dept:8001